services:
  - type: web
    name: news-dash-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn newsdash.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsdash.settings
      - key: PYTHON_VERSION
        value: 3.12
